spring:
  profiles:
    include:
      - datasource
      - mybatis
      - nacos
      - custom
    active: dev
# Tomcat
server:
  port: @server.port@
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms