spring:
  cloud:
    gateway:
      routes:
        - id: third-party-router
          uri: lb://jxs-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: product_router
          uri: lb://jxs-product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /$\{segment}


        - id: admin_router
          # loadBalance
          uri: lb://jxs-admin
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}